import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { AppProtection } from "@/components/AppProtection";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export const metadata: Metadata = {
  title: "AIScore360 - Football Match Analytics",
  description:
    "Statistical football match analytics and prediction tool This prediction is generated by AI analysis based on data and statistics. Model estimates do not guarantee the final match outcome.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ height: '100dvh' }} className="bg-bg">
      <body
        className={inter.className}
        style={{
          height: '100dvh',
          margin: 0,
          padding: 0,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          background: '#F2F2F7',
          overflowX: 'hidden',
          touchAction: 'pan-y',
        }}
      >
        <AppProtection />
        {children}
      </body>
    </html>
  );
}
